version: '3'
services:
  crawler_service:
    build: ./crawler_service
    tty: true
    depends_on:
      - rabbitmq
      - document_store_service
      - indexing_service
      - page_rank_service
    env_file:
      - ./crawler_service/.env
    volumes:
      - "./crawler_service:/usr/src/app"

  indexing_service:
    build: ./indexing_service
    command: npm run dev
    ports:
      - 3000:8080
    depends_on:
      - elasticsearch
    env_file:
      - ./indexing_service/.env
    volumes:
      - "./indexing_service:/usr/src/app"

  document_store_service:
    build: ./document_store_service
    command: npm run dev
    depends_on:
      - dynamodb
    ports:
      - 3001:8081
    env_file:
      - ./document_store_service/.env
    volumes:
      - "./document_store_service:/usr/src/app"

  page_rank_service:
    build: ./page_rank_service
    command: npm run dev
    ports:
      - 3002:8082
    depends_on:
      - rabbitmq
    env_file:
      - ./page_rank_service/.env
    volumes:
      - ./page_rank_service:/usr/src/app

  page_rank_worker:
    build: ./page_rank_service
    command: npm run pageRankWorker
    depends_on:
      - document_store_service
      - rabbitmq
    env_file:
      - ./page_rank_service/.env
    volumes:
      - ./page_rank_service:/usr/src/app

  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
      